#!/usr/bin/env python
import sys
from evoke.main import App
from evoke.errors import BaseError

if __name__ == '__main__':
    app = App()
    try:
        app.main()
    except BaseError, e:
        print str(e)
    sys.exit()
